version: '3'
services:
  web-host-nimb3s-app:
    image: nimb3s/web-host-nimb3s-app:latest
    build:
      context: .
      dockerfile: web-host-nimb3s-app.dockerfile
    container_name: Web.Host.Nimb3s.App
    restart: always
    # we can see the server running at "localhost:8080"
    ports:
      - "8080:80"
  web-host-nimb3s-cypress:
    image: nimb3s/web-host-nimb3s-cypress:latest
    build:
      context: .
      dockerfile: web-host-nimb3s-cypress.dockerfile
    container_name: Web.Host.Nimb3s.Cypress
    depends_on:
      - web-host-nimb3s-app
    # note: inside e2e container, the network allows accessing
    # "web" host under name "web-host-nimb3s-app"
    # so "curl http://web-host-nimb3s-app" would return whatever the webserver
    # in the "web-host-nimb3s-app" container is cooking
    # see https://docs.docker.com/compose/networking/
    environment:
      - CYPRESS_baseUrl=http://web-host-nimb3s-app
    command: npx cypress run
    # mount the host directory e2e/cypress and the file e2e/cypress.config.js as
    # volumes within the container
    # this means that:
    #  1. anything that Cypress writes to these folders (e.g., screenshots,
    #     videos) appears also on the Docker host's filesystem
    #  2. any change that the developer applies to Cypress files on the host
    #     machine immediately takes effect within the e2e container (no docker
    #     rebuild required).
    volumes:
      - ./cypress:/app/cypress
      - ./cypress.config.ts:/app/cypress.config.ts

      #https://github.com/cypress-io/cypress-example-docker-compose

#docker-compose build
#docker-compose up --abort-on-container-exit --exit-code-from web-host-nimb3s-cypress
#docker cp Web.Host.Nimb3s.App:/usr/share/nginx/html ./artifacts
